#!/bin/sh
set -eu
dpkg -i /archives/*fixture1*.deb
dpkg-query -W -f '${binary:Package} ${Version}\n'
case "${ERL_FLAGS:-}" in
  '') ;;
  '+JMsingle true') sed -i "s/ERL_FLAGS='/ERL_FLAGS='+JMsingle true /" /usr/lib/frameshift/launch-service /usr/bin/frameshiftctl /usr/bin/frameshift-identity /usr/bin/frameshift-maintenance ;;
  *) exit 64 ;;
esac
[ "$(cat /var/lib/frameshift/.installed-version)" = '0.1.0~dev+fixture1' ]
[ "$(stat -c '%u:%g:%a' /var/lib/frameshift/.installed-version)" = '0:0:600' ]
version=$(cut -d ' ' -f2 /usr/lib/frameshift/core/releases/start_erl.data)
exec /usr/lib/frameshift/core/releases/"$version"/elixir \
  --boot /usr/lib/frameshift/core/releases/"$version"/start_clean \
  --boot-var RELEASE_LIB /usr/lib/frameshift/core/lib /fixtures/deb-check.exs
