#!/bin/sh
set -eu

repository_root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)

# The single-quoted AWK programs intentionally contain regular expressions.
# shellcheck disable=SC2016
find "$repository_root/apps" "$repository_root/packages" \
  "$repository_root/scripts" "$repository_root/simulator" \
  -type d \( -name deps -o -name _build -o -name build -o -name node_modules \) -prune -o \
  -type f \( -name '*.ex' -o -name '*.exs' \) -print0 |
  xargs -0 awk '
    expect_content {
      if ($0 ~ /^[[:space:]]*$/) {
        print location ": expected exactly one blank line after @moduledoc" > "/dev/stderr"
        failed = 1
      }
      expect_content = 0
    }

    /^[[:space:]]*(defmodule|defimpl)[[:space:]]/ {
      location = FILENAME ":" FNR

      if (getline <= 0 || $0 !~ /^[[:space:]]*@moduledoc[[:space:]]/) {
        print location ": missing immediate @moduledoc" > "/dev/stderr"
        failed = 1
        next
      }

      hidden = FILENAME ~ /\/test\// || FILENAME ~ /_test\.exs$/ || \
        FILENAME ~ /\/migrations[\/.]/ || FILENAME ~ /\/simulator\/container\/receiver\.exs$/

      if (hidden && $0 !~ /^[[:space:]]*@moduledoc false[[:space:]]*$/) {
        print location ": migration and test modules require @moduledoc false" > "/dev/stderr"
        failed = 1
      }

      if (!hidden && $0 ~ /^[[:space:]]*@moduledoc false[[:space:]]*$/) {
        print location ": production modules require a useful @moduledoc" > "/dev/stderr"
        failed = 1
      }

      if ($0 ~ /@moduledoc[[:space:]]*"""/ && $0 !~ /"""[[:space:]]*$/) {
        while (getline > 0 && $0 !~ /"""/) {
        }
      } else if ($0 ~ /@moduledoc[[:space:]]*"""[[:space:]]*$/) {
        while (getline > 0 && $0 !~ /"""/) {
        }
      }

      if (getline <= 0 || $0 !~ /^[[:space:]]*$/) {
        print location ": expected one blank line after @moduledoc" > "/dev/stderr"
        failed = 1
      } else {
        expect_content = 1
      }
    }

    END { exit failed }
  '
