#!/bin/sh
set -eu

repository_root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)

(
  cd "$repository_root/codec"
  mise exec -- cargo fmt
)

(
  cd "$repository_root/renderer"
  mise exec -- zig fmt build.zig src
)

(
  cd "$repository_root/apps/core"
  mise exec -- mix format
  mise exec -- mix format ../../scripts/docs/*.exs
  mise exec -- mix format ../../release/*.exs
)

(
  cd "$repository_root/apps/macos"
  swift format format --in-place --recursive Sources Tests Package.swift
)

(
  cd "$repository_root/release/macos"
  swift format format --in-place --recursive Sources Tests Package.swift
)
