[package]
name = "frameshift-codec"
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"
publish = false

[dependencies]
crc32fast = "=1.5.2"
flate2 = { version = "=1.1.10", default-features = false, features = ["rust_backend"] }
kamadak-exif = "=0.6.1"
moxcms = { version = "=0.9.1", default-features = false }
png = "=0.18.1"
sha2 = "=0.11.0"

jpeg-decoder = { path = "vendor/jpeg-decoder", version = "=0.3.2-fs.1", default-features = false, features = ["platform_independent"] }

[dev-dependencies]
jpeg-encoder = { version = "=0.7.1", default-features = false, features = ["std"] }

[profile.release]
overflow-checks = true
lto = "thin"
strip = true

[lints.rust]
unsafe_code = "forbid"
