defmodule FrameshiftPlatform.Repo.Migrations.CreateCatalogProfileRevisions do
  @moduledoc """
  Creates immutable catalog profile revisions and their content identities.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:catalog_profile_revisions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:label, :text, null: false)
      add(:canonical, :text, null: false)
      add(:identity, :text, null: false)
      add(:profile_key, :text, null: false)
      add(:profile_revision, :text, null: false)
      add(:kind, :text, null: false)
      add(:classes, {:array, :text}, null: false)
      add(:evidence_state, :text, null: false, default: "candidate")
      add(:source_bindings, {:array, :map}, null: false)
      add(:actor_id, :uuid, null: false)

      add(:recorded_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:catalog_profile_revisions, [:identity],
             name: "catalog_profile_revisions_profile_content_index"
           )

    create unique_index(:catalog_profile_revisions, [:profile_key, :profile_revision],
             name: "catalog_profile_revisions_profile_revision_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:catalog_profile_revisions, [:profile_key, :profile_revision],
        name: "catalog_profile_revisions_profile_revision_index"
      )
    )

    drop_if_exists(
      unique_index(:catalog_profile_revisions, [:identity],
        name: "catalog_profile_revisions_profile_content_index"
      )
    )

    drop(table(:catalog_profile_revisions))
  end
end
